name: CI Branches

on:
  push:
    branches:
      - main
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    container: elixir:1.11
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
        - 6379:6379 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        apt-get update -y
        apt-get install -y default-mysql-client 
