name: Generate terraform docs
on:
  push:
    branches:
      - main
      - release
    tags:
      - 'v*'
jobs:
  docs:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/tags/*' }}
    steps:
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 711703446389.dkr.ecr.us-west-2.amazonaws.com
        ECR_REPOSITORY: agora/agora
        IMAGE_TAG: ${{ steps.vars.outputs.tag }}
      run: |
        echo $IMAGE_TAG
