name: Generate terraform docs
on:
  push:
    branches:
      - main
      - release
    tags:
      - 'v*'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: l7r7/sample
        tag-custom: ${{ github.ref }}
        tag-semver: |
          {{raw}}
          
    - run: echo ${{ steps.docker_meta.outputs.tags }}      
