name: Generate terraform docs
on:
  push:
    branches:
      - main
      - release
    tags:
      - 'v*'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 711703446389.dkr.ecr.us-west-2.amazonaws.com
        ECR_REPOSITORY: agora/agora
        IMAGE_TAG: ${{ github.ref }}
      run: |
        which aws
        echo $IMAGE_TAG
