
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::993450297386:role/github-deployer
    - run: aws sts get-caller-identity
