name: CI

on:
  push:
    branches:
      - main
      - release
    tags:
      - 'v*'
      
jobs:
  build-and-push-image-on-br: # tags
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' }}
    steps:
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/} ## tags - version such as v1.0
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
  build-and-push-image-on-tags: # tags
    runs-on: ubuntu-latest
    steps:  
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/} ## tags - version such as v1.0
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION    
