name: Weekly Team Sync
on:
  push:
    branches:
      - main  
jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          labels: "weekly sync, docs-team"
          title: "Update current Helm Charts Version "
          body: |
            ### Update current Helm Charts Version 

            - [ ] Karpenter (https://github.com/opszero/terraform-aws-kubespot/blob/main/variables.tf#L426)
            - [ ] Metric Server (https://github.com/opszero/terraform-aws-kubespot/blob/main/variables.tf#L384)

            ### Change the value of variables in variables.tf
            
            variable "metrics_server_version" {
              default = "3.8.2"  
            }   

            variable "karpenter_version" {
              default = "v0.9.1"
            }
            
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
